name: gfsa_graph_pcqm
channels:
  - defaults
dependencies:
  - pip=23.2.1
  - python=3.9.7
  - pip:
    - cython==3.0.2
    - lightning-utilities==0.9.0
    - networkx==3.1
    - numpy==1.25.2
    - ogb==1.3.2
    - pandas==2.1.0
    - protobuf==4.24.3
    - python-dateutil==2.8.2
    - python-louvain==0.16
    - pytorch-lightning==1.3.1
    - torch==1.13.0+cu117
    - torch-geometric==1.7.2
    - torch-scatter==2.1.1+pt113cu117
    - torch-sparse==0.6.15+pt113cu117
    - torchaudio==0.13.0+cu117
    - torchmetrics==0.6.0
    - torchvision==0.14.0+cu117
